version: "3"
services:
  app:
    env_file:
      - .development.env
    container_name: nest_api
    restart: always
    build: .
    ports:
      - "$PORT:$PORT"
    links:
      - postgres
  mysql:
    image: mysql
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
